"""
Concierge Escalation Tickets

Persists escalation tickets so they survive server restarts and are
accessible to the operator dashboard.
"""

from datetime import datetime
from uuid import uuid4

from sqlalchemy import DateTime, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from db.models.core import Base, TimestampMixin


class ConciergeEscalationModel(Base, TimestampMixin):
    """
    Escalation ticket created when a guest needs human intervention.

    ticket_id is the ESC-XXXXXXXX string generated by EscalationService.
    """

    __tablename__ = "concierge_escalations"

    ticket_id: Mapped[str] = mapped_column(String(50), primary_key=True)

    # Session reference
    session_token: Mapped[str] = mapped_column(String(50), nullable=False, index=True)

    # Guest info (denormalized for fast dashboard access)
    guest_name: Mapped[str] = mapped_column(String(255), nullable=False)
    guest_phone: Mapped[str | None] = mapped_column(String(50))
    guest_email: Mapped[str | None] = mapped_column(String(255))
    property_name: Mapped[str] = mapped_column(String(255), nullable=False)
    property_code: Mapped[str] = mapped_column(String(100), nullable=False, index=True)

    # Escalation details
    reason: Mapped[str] = mapped_column(String(50), nullable=False)
    priority: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending", index=True)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    last_message: Mapped[str | None] = mapped_column(Text)

    # Conversation snapshot
    conversation_history: Mapped[dict] = mapped_column(JSONB, default=list, server_default="[]")

    # Assignment / resolution
    assigned_to: Mapped[str | None] = mapped_column(String(255))
    watchers: Mapped[list] = mapped_column(JSONB, default=list, server_default="[]")
    watchers_notified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    vendor_name: Mapped[str | None] = mapped_column(String(255))
    vendor_phone: Mapped[str | None] = mapped_column(String(50))
    vendor_eta_minutes: Mapped[int | None] = mapped_column()
    vendor_status: Mapped[str | None] = mapped_column(String(50))
    guest_updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    guest_update_status: Mapped[str | None] = mapped_column(String(50))
    guest_update_due_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    guest_update_note: Mapped[str | None] = mapped_column(Text)
    resolution_notes: Mapped[str | None] = mapped_column(Text)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_escalation_status_priority", "status", "priority"),
        Index("ix_escalation_property", "property_code"),
    )
