-- Migration 014 — Agent Architecture Support
--
-- Adds columns and tables required by:
--   - PMSSyncAgent (pms_synced_at on concierge_sessions)
--   - EscalationHandoffAgent (SLA breach flags + resolve fields on concierge_escalations)
--   - KnowledgeCuratorAgent (knowledge_gap_drafts table)
--   - PropertyRouter (properties table tenant scoping + active flag)
--
-- Run:
--     psql $DATABASE_URL -f migrations/014_agent_architecture.sql
--
-- Or via alembic:
--     alembic upgrade head

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. PMS Sync: stamp when each session was last reconciled against PMS
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE concierge_sessions
    ADD COLUMN IF NOT EXISTS pms_synced_at TIMESTAMPTZ DEFAULT NULL;

COMMENT ON COLUMN concierge_sessions.pms_synced_at IS
    'Last time PMSSyncAgent reconciled this session against the live PMS. '
    'NULL means never synced. Sync runs hourly for active sessions.';

CREATE INDEX IF NOT EXISTS idx_concierge_sessions_pms_synced_at
    ON concierge_sessions (pms_synced_at ASC NULLS FIRST)
    WHERE status = 'active';


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Escalation SLA breach tracking
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE concierge_escalations
    ADD COLUMN IF NOT EXISTS acknowledged_at    TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS resolved_at        TIMESTAMPTZ DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS assigned_to        TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS resolution_code    TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS ack_sla_breached   BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS resolve_sla_breached BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notes              JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN concierge_escalations.ack_sla_breached IS
    'Set TRUE by EscalationHandoffAgent when ack SLA is breached. '
    'Urgent: 15min, High: 1hr, Medium: 4hr.';
COMMENT ON COLUMN concierge_escalations.resolve_sla_breached IS
    'Set TRUE by EscalationHandoffAgent when resolve SLA is breached. '
    'Urgent: 1hr, High: 4hr, Medium: 24hr.';

CREATE INDEX IF NOT EXISTS idx_escalations_open_status
    ON concierge_escalations (status, created_at ASC)
    WHERE status IN ('pending', 'acknowledged', 'in_progress');


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Knowledge Curator: gap drafts table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS knowledge_gap_drafts (
    draft_id            TEXT PRIMARY KEY,
    property_code       TEXT NOT NULL,
    operator_id         TEXT NOT NULL,
    question            TEXT NOT NULL,
    answer_hint         TEXT NOT NULL DEFAULT '',
    gap_ids             JSONB NOT NULL DEFAULT '[]',
    occurrence_count    INTEGER NOT NULL DEFAULT 0,
    status              TEXT NOT NULL DEFAULT 'pending_review',   -- pending_review | approved | rejected
    reviewed_by         TEXT DEFAULT NULL,
    reviewed_at         TIMESTAMPTZ DEFAULT NULL,
    rejection_reason    TEXT DEFAULT NULL,
    indexed_doc_id      TEXT DEFAULT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE knowledge_gap_drafts IS
    'FAQ entry drafts generated by KnowledgeCuratorAgent from clustered knowledge gaps. '
    'Operator reviews, fills in answer, and approves → indexed into vector store.';

CREATE INDEX IF NOT EXISTS idx_gap_drafts_pending
    ON knowledge_gap_drafts (property_code, occurrence_count DESC)
    WHERE status = 'pending_review';

CREATE INDEX IF NOT EXISTS idx_gap_drafts_property_question
    ON knowledge_gap_drafts (property_code, lower(question));


-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Knowledge gaps: resolved flag (enables curator to mark gaps as closed)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE knowledge_gaps
    ADD COLUMN IF NOT EXISTS resolved      BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS resolved_at   TIMESTAMPTZ DEFAULT NULL;

CREATE INDEX IF NOT EXISTS idx_knowledge_gaps_unresolved
    ON knowledge_gaps (property_code, created_at DESC)
    WHERE resolved = FALSE;


-- ─────────────────────────────────────────────────────────────────────────────
-- 5. Properties table: tenant scoping + active flag (for PropertyRouter tier 2)
-- ─────────────────────────────────────────────────────────────────────────────
-- Note: properties table may already exist from a prior migration.
-- These are additive only.
DO $$
BEGIN
    -- tenant_id (for PropertyRouter cross-tenant safety)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'properties' AND column_name = 'tenant_id'
    ) THEN
        ALTER TABLE properties ADD COLUMN tenant_id TEXT DEFAULT 'default';
        COMMENT ON COLUMN properties.tenant_id IS
            'Tenant scope. PropertyRouter WHERE-clause always includes tenant_id '
            'so cross-tenant data is structurally impossible.';
    END IF;

    -- active flag (PropertyRouter skips inactive properties)
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'properties' AND column_name = 'active'
    ) THEN
        ALTER TABLE properties ADD COLUMN active BOOLEAN DEFAULT TRUE;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_properties_tenant_code
    ON properties (tenant_id, property_code)
    WHERE active = TRUE;
