"""
_dashboard_html.py — AUTO-GENERATED BY scripts/build_dashboard.py

Do not edit manually. Regenerate with:
    python3 scripts/build_dashboard.py

Contains the complete Oyvoda operator dashboard HTML as a Python string.
Generated from oyvoda-v10.jsx. Loaded once at import time.
Zero file I/O at request time. Works in any deployment environment.
"""

# This file is regenerated by build_dashboard.py whenever oyvoda-v10.jsx changes.
# The HTML contains the full React dashboard with all JS inlined.
# ~320KB compiled JS + HTML shell = ~323KB total.

DASHBOARD_HTML: str = ""
# NOTE: Content populated by build_dashboard.py — run it to regenerate
